CREATE TABLE t_term(
f_termId	INT IDENTITY,
f_version	INT NOT NULL DEFAULT 0,
f_name	NVARCHAR(15) NOT NULL,
f_detailContent	NVARCHAR(MAX) NOT NULL,
f_type	TINYINT NOT NULL,
f_applicableTarget	TINYINT NOT NULL,
f_versionDescription	NVARCHAR(200) NOT NULL,
f_status	TINYINT NOT NULL DEFAULT 1,
f_effectiveTime	DATETIME2(3) NOT NULL DEFAULT '1900-01-01 00:00:00',
f_updateTime	DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME()
)