CREATE TABLE t_member(
	f_memberId INT PRIMARY KEY IDENTITY,
	f_account VARCHAR(20) NOT NULL UNIQUE,
	f_hash VARCHAR(100) NOT NULL,
	f_email VARCHAR(254) NOT NULL,
	f_phone INT NOT NULL UNIQUE,
	f_name NVARCHAR(50) NOT NULL,
	f_photoUrl NVARCHAR(100) NOT NULL,
	f_birthday DATE NOT NULL DEFAULT '0001-01-01',
	f_gender TINYINT NOT NULL DEFAULT 0,
	f_height INT NOT NULL,
	f_weight INT NOT NULL,
	f_status BIT NOT NULL DEFAULT 1,
	f_absenceTime TINYINT NOT NULL DEFAULT 0,	
	f_allowGroupClass DATE NOT NULL DEFAULT '0001-01-01',
	f_membershipExpiry DATE NOT NULL DEFAULT '0001-01-01',
	f_createTime DATETIME NOT NULL DEFAULT GETDATE(),
	f_updateTime DATETIME NOT NULL DEFAULT GETDATE()
)