CREATE TABLE t_order(
	f_orderId	INT IDENTITY,
	f_planId	INT NOT NULL,
	f_planType	TINYINT NOT NULL,
	f_planName	NVARCHAR(20) NOT NULL,
	f_orderNumber	BIGINT NOT NULL UNIQUE,
	f_state	TINYINT NOT NULL,
	f_amount	INT NOT NULL,
	f_method	TINYINT NOT NULL,
	f_remark	NVARCHAR(50) NOT NULL DEFAULT '',
	f_createTime	DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
	f_updateTime	DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME()
)