CREATE TABLE t_singleEntryPass(
	f_singleEntryPassId	INT NOT NULL IDENTITY PRIMARY KEY,
	f_orderId	INT NOT NULL,
	f_expiry	DATE	NOT NULL DEFAULT SYSUTCDATETIME(),
	f_status	TINYINT NOT NULL DEFAULT 3,
	f_createTime	DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
	f_updateTime	DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
	CONSTRAINT FK_t_singleEntryPass_t_order FOREIGN KEY (f_orderId) REFERENCES t_order(f_orderId)
)