CREATE TABLE [dbo].[t_member] (
    [f_memberId]                 INT            IDENTITY (1, 1) NOT NULL,
    [f_account]                  VARCHAR (20)   NOT NULL,
    [f_hash]                     VARCHAR (100)  NOT NULL,
    [f_email]                    VARCHAR (254)  CONSTRAINT [DF_t_member_f_email] DEFAULT ('') NOT NULL,
    [f_phone]                    INT            NOT NULL,
    [f_name]                     NVARCHAR (50)  CONSTRAINT [DF_t_member_f_name] DEFAULT ('') NOT NULL,
    [f_photoUrl]                 NVARCHAR (100) CONSTRAINT [DF_t_member_f_photoUrl] DEFAULT ('') NOT NULL,
    [f_birthday]                 DATE           DEFAULT ('0001-01-01') NOT NULL,
    [f_gender]                   TINYINT        DEFAULT ((0)) NOT NULL,
    [f_height]                   INT            CONSTRAINT [DF_t_member_f_height] DEFAULT ((0)) NOT NULL,
    [f_weight]                   INT            CONSTRAINT [DF_t_member_f_weight] DEFAULT ((0)) NOT NULL,
    [f_status]                   BIT            DEFAULT ((1)) NOT NULL,
    [f_absenceTime]              TINYINT        DEFAULT ((0)) NOT NULL,
    [f_allowGroupClass]          DATE           DEFAULT ('0001-01-01') NOT NULL,
    [f_membershipExpiry]         DATE           DEFAULT ('0001-01-01') NOT NULL,
    [f_createTime]               DATETIME       DEFAULT (getdate()) NOT NULL,
    [f_updateTime]               DATETIME       DEFAULT (getdate()) NOT NULL,
    [f_phoneVerified]            BIT            DEFAULT ((0)) NOT NULL,
    [f_emergencyContactName]     VARCHAR (50)   DEFAULT ('') NOT NULL,
    [f_emergencyContactPhone]    INT            DEFAULT ((0)) NOT NULL,
    [f_emergencyContactRelation] VARCHAR (10)   DEFAULT ('') NOT NULL,
    PRIMARY KEY CLUSTERED ([f_memberId] ASC),
    UNIQUE NONCLUSTERED ([f_account] ASC),
    UNIQUE NONCLUSTERED ([f_phone] ASC)
);

